import { GoogleGenAI, Modality } from "@google/genai";

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = (error) => reject(error);
  });
};

export const generateHugImage = async (image1: File, image2: File, intensity: number): Promise<string> => {
  if (!process.env.API_KEY) {
    // In a real app, you might want to show this to the user in a more friendly way.
    // For this example, we'll throw an error.
    throw new Error("API_KEY environment variable is not set. Please configure it to use the AI features.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const image1Base64 = await fileToBase64(image1);
  const image2Base64 = await fileToBase64(image2);

  let intensityDescriptor = "a warm, realistic, and affectionate embrace";
  if (intensity < 33) {
      intensityDescriptor = "a gentle, light hug, maybe a side-hug, in a tender and subtle moment";
  } else if (intensity > 67) {
      intensityDescriptor = "a tight, close hug, showing deep affection and strong connection";
  }

  const prompt = `Merge these two images into one photorealistic image. The resulting image should show the two main subjects from the images hugging each other in ${intensityDescriptor}. Blend the styles and lighting seamlessly. Create a cohesive background that complements the new scene, as if they were in the same place at the same time. The final output must be just the image.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { text: prompt },
        {
          inlineData: {
            data: image1Base64,
            mimeType: image1.type,
          },
        },
        {
          inlineData: {
            data: image2Base64,
            mimeType: image2.type,
          },
        },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  // More robustly find the image part in the response.
  const imagePart = response.candidates?.[0]?.content?.parts?.find(
    (part) => part.inlineData && part.inlineData.mimeType.startsWith('image/')
  );

  if (imagePart?.inlineData) {
    const base64ImageBytes: string = imagePart.inlineData.data;
    const mimeType = imagePart.inlineData.mimeType;
    return `data:${mimeType};base64,${base64ImageBytes}`;
  }
  
  // If no image is found, check for a block reason.
  const blockReason = response.promptFeedback?.blockReason;
  if (blockReason) {
      throw new Error(`Image generation failed. Reason: ${blockReason}. Please adjust your images or prompt and try again.`);
  }

  throw new Error("No image was generated by the API. Please try again.");
};